import { UniversityData } from './types';

export const DEFAULT_DATA: UniversityData = {
  "NOMBRE DE LA UNIVERSIDAD": "UNIVERSIDAD ------------ ------------",
  "ABREVIATURA UNIVERSIDAD": "AMAZING U",
  "FACULTAD": "FACULTAD DE INGENIERIA DE ------------",
  "ESCUELA": "ESCUELA PROFESIONAL DE INGENIERÍA EN ------------",
  "PROGRAMA DE ESTUDIOS": "INGENIERÍA EN ------------",
  "CODIGO PROGRAMA": "P13",
  "DIRECTOR DEL PROGRAMA DE ESTUDIOS": "",
  "DEPARTAMENTO ACADÉMICO": "",
  "DIRECTOR DEL DEPARTAMENTO ACADÉMICO": "",
  "CODIGO LOCAL": "SL01",
  "labs": []
};